name: SORACOM Orbit CI/CD

on:
  push:
  workflow_dispatch:

env:
  COVERAGE: g

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kenichiro-kimura/orbit-assemblyscript:latest
      options: --cpus 1
      credentials:
        username: ${{ secrets.GHCR_CONTAINER_REGISTRY_USER }}
        password: ${{ secrets.GHCR_CONTAINER_REGISTRY_PASSWORD }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: initialize
        run: npm run init
      - name: copy libs
        run: cp -r /workspaces/orbit-sdk-assemblyscript ../
      - name: build optimized
        run: npm run build:optimized
      - name: upload assets
        uses: actions/upload-artifact@v2
        with:
          name: soracom-orbit
          path: build/soralet-optimized.wasm

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/staging'
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: soracom-orbit
      - name: deploy
        uses: kenichiro-kimura/action-soracom-upload-soralet@1.1.0
        id: deploy
        if: github.ref == 'refs/heads/master'
        with:
          soracom_auth_key: ${{ secrets.AUTH_KEY }}
          soracom_auth_key_id: ${{ secrets.AUTH_KEY_ID}}
          soracom_coverage: ${{ env.COVERAGE }}
          soracom_soralet_id: button-global-to-japan
          soracom_soralet_filename: soralet-optimized.wasm
          soracom_delete_old_soralet: true
      - name: deploy-staging
        uses: kenichiro-kimura/action-soracom-upload-soralet@1.1.0
        id: deploy-staging
        if: github.ref == 'refs/heads/staging'
        with:
          soracom_auth_key: ${{ secrets.AUTH_KEY }}
          soracom_auth_key_id: ${{ secrets.AUTH_KEY_ID}}
          soracom_coverage: ${{ env.COVERAGE }}
          soracom_soralet_id: button-global-to-japan-stg
          soracom_soralet_filename: soralet-optimized.wasm
          soracom_delete_old_soralet: true
      - name: view pruduction result
        if: github.ref == 'refs/heads/master'
        env:
          result: ${{steps.deploy.outputs.result}}
        run: echo $result
      - name: view staging result
        if: github.ref == 'refs/heads/staging'
        env:
          result: ${{steps.deploy-staging.outputs.result}}
        run: echo $result
